{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "localega.fullname" . }}-postgres-policy
  labels:
    app: {{ template "localega.name" . }}-postgres-policy
spec:
  podSelector:
    matchLabels:
      app: {{ template "localega.name" . }}-db
      release: {{ .Release.Name | quote }}
  ingress:
    # Allow inbound connections
    - ports:
      - port: 5432
    {{- if not .Values.networkPolicy.allowExternal }}
      from:
      - podSelector:
          matchLabels:
            {{ template "localega.fullname" . }}-client: "true"
    {{- end }}
    # Allow prometheus scrapes
    - ports:
      - port: 9187
{{- end }}
