apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-verify
  labels:
    role: verify
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.verify.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: verify
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-verify
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-verify
        role: verify
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: verify
        image: "{{ .Values.base.image }}:{{ .Values.base.imageTag }}"
        imagePullPolicy: {{ .Values.base.imagePullPolicy | quote }}
        command: ["gosu", "lega", "ega-verify"]
        env:
        - name: BROKER_CONNECTION_ATTEMPTS
          value: {{ .Values.config.broker_connection_attempts | quote }}
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.fullname" . }}-mq{{ end }}
        - name: BROKER_PORT
          value: {{.Values.mq.port | quote }}
        - name: BROKER_RETRY_DELAY
          value: {{ .Values.config.broker_retry_delay | quote }}
        - name: BROKER_USERNAME
          value: {{ .Values.config.broker_username | quote }}
        - name: KEYSERVER_ENDPOINT
          value: {{ if .Values.config.keyserver_host }}{{ .Values.config.keyserver_host }}{{ else }}https://{{ template "localega.fullname" . }}-keys{{ end }}:{{ .Values.keys.port}}{{ .Values.config.keyserver_endpoint}}
        - name: KEYSERVER_HOST
          value: {{ if .Values.config.keyserver_host }}{{ .Values.config.keyserver_host | quote }}{{ else }}{{ template "localega.fullname" . }}-keys{{ end }}
        - name: KEYSERVER_PORT
          value: {{ .Values.keys.port | quote }}
        - name: POSTGRES_HOST
          value: {{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-db-secret
              key: postgres_password
        - name: POSTGRES_TRY
          value: {{ .Values.config.postgres_try | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.config.postgres_user | quote }}
        - name: VAULT_DRIVER
          value: {{ .Values.config.data_storage_type | quote }}
        - name: VAULT_URL
          value: {{ required "A valid .Values.config.data_storage_url entry required!" .Values.config.data_storage_url | quote }}
        - name: LEGA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-password
              key: password
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-s3-keys
              key: access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-s3-keys
              key: secret_key
      restartPolicy: Always