apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-dataedge
  labels:
    role: dataedge
    app: {{ template "localega.name" . }}-dataegde
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.dataedge.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.dataedge.replicaCount }}
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-dataedge
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-dataedge
        role: dataedge
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: dataedge
        image: "{{ .Values.dataedge.repository }}:{{ .Values.dataedge.imageTag }}"
        imagePullPolicy: {{ .Values.dataedge.imagePullPolicy | quote }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: no-oss
        - name: FILEDATABASE_SERVERS
          value: "{{ if .Values.config.filedatabase_host }}{{ .Values.config.filedatabase_host }}:{{ .Values.config.filedatabase_port }}{{ else }}{{ template "localega.fullname" . }}-filedatabase:{{ .Values.filedatabase.servicePort }}{{ end }}"
        - name: KEYS_SERVERS
          value: "{{ if .Values.config.keyserver_host }}{{ .Values.config.keyserver_host }}:{{ .Values.config.keyserver_port }}{{ else }}{{ template "localega.fullname" . }}-keys:{{ .Values.keys.servicePort }}{{ end }}"
        - name: RES_SERVERS
          value: "{{ if .Values.config.res_host }}{{ .Values.config.res_host }}:{{ .Values.config.res_port }}{{ else }}{{ template "localega.fullname" . }}-res:{{ .Values.res.servicePort }}{{ end }}"
        - name: EGA_EGA_EXTERNAL_URL
          value: "https://ega.ebi.ac.uk:8051/elixir/data/files/"
        - name: EGA_EGA_CRAM_FASTA_A
          value: "/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta"
        - name: EGA_EGA_CRAM_FASTA_B
          value: "/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fastb"
        - name: DB_URL
          value: "jdbc:postgresql://{{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}/{{ .Values.config.postgres_db_name }}"
        - name: JWTKEY
          valueFrom:
            configMapKeyRef:
              name: {{ template "localega.name" . }}-dataedge-public-key
              key: public.key
        ports:
        - name: dataedge
          containerPort: {{ .Values.dataedge.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: dataedge
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
{{ toYaml .Values.dataedge.resources | indent 10 }}