apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-filedatabase
  labels:
    role: filedatabase
    app: {{ template "localega.name" . }}-filedatabase
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.filedatabase.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.filedatabase.replicaCount }}
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-filedatabase
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-filedatabase
        role: filedatabase
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: filedatabase
        image: "{{ .Values.filedatabase.repository }}:{{ .Values.filedatabase.imageTag }}"
        imagePullPolicy: {{ .Values.filedatabase.imagePullPolicy | quote }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: no-oss
        - name: DB_SCHEMA
          value: {{ .Values.config.postgres_db_schema | quote }}
        - name: DB_USERNAME
          value: {{ .Values.config.postgres_user | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-db-secret
              key: postgres_password
        - name: DB_URL
          value: "jdbc:postgresql://{{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}:5432/{{ .Values.config.postgres_db_name }}"
        ports:
        - name: filedatabase
          containerPort: {{ .Values.filedatabase.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: filedatabase
          initialDelaySeconds: 60
          periodSeconds: 30
        resources:
{{ toYaml .Values.filedatabase.resources | indent 10 }}