apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-mapper
  labels:
    role: mapper
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.mapper.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-mapper
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-mapper
        role: mapper
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: mapper
        image: "{{ .Values.mapper.repository }}:{{ .Values.mapper.imageTag }}"
        imagePullPolicy: {{ .Values.mapper.imagePullPolicy | quote }}
        command: ["gosu", "lega", "ega-id-mapper"]
        args: ["--log", "debug"]
        env:
        - name: DEFAULT_LOG
          value: {{ .Values.config.log | quote }}
        - name: BROKER_CONNECTION_ATTEMPTS
          value: {{ .Values.config.broker_connection_attempts | quote }}
        - name: BROKER_ENABLE_SSL
          value: {{ .Values.config.broker_enable_ssl | quote }}
        - name: BROKER_HEARTBEAT
          value: {{ .Values.config.broker_heartbeat | quote }}
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.fullname" . }}-mq{{ end }}
        - name: BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-mq-pass
              key: password
        - name: BROKER_PORT
          value: {{.Values.mq.port | quote }}
        - name: BROKER_RETRY_DELAY
          value: {{ .Values.config.broker_retry_delay | quote }}
        - name: BROKER_USERNAME
          value: {{ .Values.config.broker_username | quote }}
        - name: BROKER_VHOST
          value: "/"
        - name: POSTGRES_HOST
          value: {{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-db-secret
              key: postgres_password
        - name: POSTGRES_SSLMODE
          value: {{ .Values.config.postgres_sslmode | quote }}
        - name: POSTGRES_SSLCERT
          value: ""
        - name: POSTGRES_TRY
          value: {{ .Values.config.postgres_try | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.config.postgres_user | quote }}
        resources:
{{ toYaml .Values.mapper.resources | indent 10 }}
      restartPolicy: Always
